apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: dotnet-test-app
  namespace: argocd
spec:
  destination:
    namespace: dotnet-test-app
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: helm/webapp
    repoURL: "https://github.com/quazini/dotnet-test-app-CircleCi.git"
    targetRevision: master
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

    