version: 2.1

orbs:
  windows: circleci/windows@2.2.0
  docker: circleci/docker@2.1.2
  helm: circleci/helm@1.2.0

jobs:
  test:
    executor:
      name: windows/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "SimpleCalc/SimpleCalc.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "SimpleCalc/SimpleCalc.csproj" }}
      - run:
          name: "Run Application Tests"
          command: dotnet.exe test -v n --results-directory:test_coverage --collect:"Code Coverage"
      - store_artifacts:
          path: C:\Users\circleci\project\test_coverage
  build:
    description: Build application with Release configuration
    executor:
      name: docker/docker
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
      - run: 
          name: Build Docker image
          command: |
            docker build -t $DOCKER_REPOSITORY:$CIRCLE_SHA1 .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push $DOCKER_REPOSITORY:$CIRCLE_SHA1
  deploy-job:
    executor:
      name: docker/docker
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 6e:fb:d0:43:f9:cf:09:37:2b:ce:35:2c:f3:b0:40:1f
      - run: 
          name: Updating Helm Chart 
          command: |
            git config --global user.email nanvenfaden@gmail.com
            git config --global user.name  quazini
            git checkout master
            echo "updating image tag in values file"
            sed -i "s,tag:.*,tag:\$CIRCLE_SHA1," helm/webapp/values.yaml
            git add . && git commit -m "update image tag"
            git push
workflows:
  build-and-test:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy-job:
          requires:
            - build
